### ISSUE TITLE
现在进展如何？

### ISSUE THREAD

**Issue by quancs** [CQUtug/TeXProposal#3]
似乎过去很久了，不知道进展如何？？？？

**Comment by nanmu42** [comment]
提案当时似乎得了个奖，后来好像就没什么声音了。

LaTeX毕竟是小众，有些事有心无力。

共勉。

**Comment by nanmu42** [comment]
不过有一点一定要提一下，我们学校有自己的CTAN镜像了。

https://mirrors.cqu.edu.cn/

**Comment by quancs** [comment]
@nanmu42 是的，这个我知道。对了，你好像是CQUThesis的作者。我最近正在写毕业论文，我想做一个重庆大学毕业论文的word模板，不知道你有没有兴趣一起？我觉得word模板的意义和latex模板的意义同等重要。因为我在写毕业论文的时候，很想用latex模板，但是用latex模板有一个问题就是：如果我需要微调生成的格式的话，几乎不可能（需要从头学习latex语言，修改CQUThesis模板）。但是word模板就可以规避掉这个问题，同时学校似乎还提供word版的格式矫正。
